### ISSUE TITLE
wallet design

### ISSUE THREAD

**Issue by jbibla** [cosmos/voyager#1044]
UI Version: 0.9.1

modal:
- could be larger with a better use of a grid
- confirmation buttons are usually in the bottom right
- tooltips can't be transparent

wallet:
- send button should be inside of container width of wallet
- checkTx error

<img width="609" alt="screen shot 2018-07-29 at 9 02 57 am" src="https://user-images.githubusercontent.com/6021933/43366679-bd778770-930f-11e8-84ca-51315ce9c9f5.png">

<img width="1440" alt="screen shot 2018-07-29 at 9 13 29 am" src="https://user-images.githubusercontent.com/6021933/43366677-ba56ba7a-930f-11e8-9579-f628a7b38d05.png">

**Comment by jbibla** [comment]
modal:
- [ ] could be larger with a better use of a grid  (#1044)
- [ ] confirmation buttons are usually in the bottom right (#1044)
- [ ] tooltips can't be transparent (#1075)

wallet:
- [ ] send button should be inside of container width of wallet (#1044)
- [ ] checkTx error (#1071)
