### ISSUE TITLE
Require strict mode.

### ISSUE THREAD

**Issue by NodeGuy** [cosmos/voyager#1051]
- [ ] https://github.com/cosmos/voyager/issues/1182
- [ ] https://github.com/cosmos/voyager/issues/1183
- [ ] https://github.com/cosmos/voyager/issues/1184
- [ ] https://github.com/cosmos/voyager/issues/1185
- [ ] Use ESLint to enforce this: https://eslint.org/docs/rules/strict

**Comment by fedekunze** [comment]
@NodeGuy does this just require to add `"use strict";`  to the beginning of each file ?

**Comment by fedekunze** [comment]
@jbibla do you remember why do we need to split this issue ?

**Comment by NodeGuy** [comment]
We need to split this issue because if we make strict mode mandatory for all files then we're going to get a ton of non-compliance issues that need to be fixed all at once.  Today I'm going to compile a list of all of the JavaScript files and create new issues to tackle groups of them at a time.  Once all of the files are in compliance then we can make the ESLint change.

**Comment by NodeGuy** [comment]
Blocked by https://github.com/cosmos/voyager/issues/1182, https://github.com/cosmos/voyager/issues/1183, https://github.com/cosmos/voyager/issues/1184, and https://github.com/cosmos/voyager/issues/1185.

**Comment by faboweb** [comment]
I consider this ticket done in this sprint. The scope was to split it.

**Comment by NodeGuy** [comment]
Closing because Babel is already enabling strict mode for us with the `es2015` preset.  We should open this again in the future if we stop using Babel (or that preset).
