### ISSUE TITLE
Remove binary from main process

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1341]
We do not want to rely on a binary for Voyager. We want full control over our process. This enables us to put Voyager in the web.

Blocked on:
#1339 
#1340 

Scope:
- [ ] remove gaia binary from main process
- [ ] remove ipc messages
- [ ] reduce main process to starting the Voyager Vue application

**Comment by faboweb** [comment]
Done
