### ISSUE TITLE
Display proposals index

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1401]
Scope:
- [x] create proposal overview related getter functions in lcdClient
- [x] create a governance module
- [ ] display proposals
- [x] write tests for module
- [x] write tests for lcdClient

**Comment by NodeGuy** [comment]
Spec: https://github.com/cosmos/cosmos-sdk/blob/develop/docs/spec/governance/state.md#proposals

Endpoints: https://github.com/cosmos/cosmos-sdk/blob/develop/x/gov/client/rest/rest.go

**Comment by faboweb** [comment]
> The OpenAPI spec doesn't include governance yet.

The spec doesn't even contain staking yet. Still some miles to go.

> how will we test this—with a local node

Yes. This should work as there are tests for it here: https://github.com/cosmos/cosmos-sdk/blob/develop/cmd/gaia/cli_test/cli_test.go#L318

**Comment by fedekunze** [comment]
Some work was done in on the following commit: https://github.com/cosmos/voyager/pull/1463/commits/516ab541204b5a584f4735718ce9be0a36516faa 

Note: The changes are the deletions on that commit
