### ISSUE TITLE
Proposal creation

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1402]
Scope:
- [x] create proposal creation post function in lcdClient
- [x] create proposal creation actions in governance module
- [ ] attach proposal creation to view components
- [x] write tests for actions
- [x] write tests for lcdClient functions

**Comment by NodeGuy** [comment]
Does "attach proposal creation to view components" mean to implement [this design](https://app.zeplin.io/project/59e66beff6721ea8bf562e5b/screen/5bc0ecbc29495f5fbbea38ba)?

**Comment by NodeGuy** [comment]
Blocked by https://github.com/cosmos/voyager/issues/1517, which occurs when a new proposal is created.
