### ISSUE TITLE
Password on transaction flow

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1638]
As of user feedback we decided to not persist the password in the state. As a result we will ask the password on every transaction.

Scope:
- [x] The transaction modals will need a new input field to enter the password.
  - Note: the password needs to be passed through to the send function
- [x] Design the new modal signing flow #1735
- [ ] On login the user doesn't need to enter a password #1718 
  - We could just remember the last login and skip the login screen (yeah!)

**Comment by jbibla** [comment]
> On login the user doesn't need to enter a password

i think we should let users choose if they want this

**Comment by jbibla** [comment]
thanks for the input @cwgoes! i think this makes a lot of sense and was excited to hear the idea!!

> Often I might open Voyager just to view state

true, but i feel some folks might like the comfort of knowing that if someone else uses their computer or if they are on a public machine that a password will be required to view "their state"

voyager on the web will provide a hub-wide state view - but for accounts which include an account name and certain preferences over time, this could feel like an invasion of sorts. that's why i like giving the user the option (a checkbox that asks whether or not they want to enter their password to view their state)...

> we no longer need to persist the password in state 

yep. this sounds great.

**Comment by faboweb** [comment]
isn't the state public anyway?

**Comment by jbibla** [comment]
technically, yes. but "logging in as someone else" doesn't feel right. what your proposing would mean you could pick any address and use voyager as if it were your own account ... right?

**Comment by faboweb** [comment]
Note: This would probably mean 2 passwords. One for the local account. One for the private key. Am I correct?

**Comment by jbibla** [comment]
good question - we'll discuss!

**Comment by faboweb** [comment]
- we have one password for the private key (for signing)
- we have no password for the settings (for logging in)
- we auto login
- we sign on a transaction

**Comment by fedekunze** [comment]
> On login the user doesn't need to enter a password
    We could just remember the last login and skip the login screen (yeah!)

I'd change this to remember the last address for querying purposes

**Comment by faboweb** [comment]
The last feature needs more thinking is handled in #1953
