### ISSUE TITLE
Remove session sign in/up for read-only purposes

### ISSUE THREAD

**Issue by fedekunze** [cosmos/voyager#1718]
Often I might open Voyager just to view state / check if I've received a transaction, for which I will never need my password (or Ledger).

_Originally posted by @cwgoes in https://github.com/cosmos/voyager/issues/1638#issuecomment-441657345_

**Scope**:
Part 1: "explorer mode"
- [ ] Remove balance header
- [ ] Hide my delegations
- [ ] Hide transactions
- [ ] Hide wallet
- [ ] Opening action modal points to sign in
- [ ] Hide pref page
- [ ] disable routes (redirect to session page)

Part 2:
- [ ] Disable analytics
- [ ] Start in "explorer mode"
- [ ] Add sign in button
- [ ] Sign out brings you to "explorer mode"

**Comment by sabau** [comment]
I commented/removed the: `show balance if user hasBalance logic` from the TmPage PR, one conflict less 🎉

**Comment by jbibla** [comment]
> in "explorer mode": Hide transactions

we discussed hiding the personal transactions tab but not the "all transactions" tab (which doesn't exist yet)

> in "explorer mode": Hide pref page

i don't think we should hide this page, i think we should ask the user to sign up / sign in to save preferences.

> in "explorer mode": Disable analytics

why?

> Sign out brings you to "explorer mode"

we're going to need a home page 😄

**Comment by jbibla** [comment]
> Because the user isn't able to opt in. 

i think we need to default to _some amount_ of analytics. i am very open to letting users opt out. re: cookies - we should investigate the requirements here more closely.

> ok, then hide user specific stuff like analytics

i think our approach should be to hide as little as possible - but prompt people to sign in to save their settings (in the case of the pref page).

> yes but let's hide the transactions until we have "all transactions"

sure sounds good!

**Comment by faboweb** [comment]
Maybe split:
- [ ] start in explorer mode
- [ ] add signin / signout

**Comment by fedekunze** [comment]
updated description with the 2 parts and their scope of work
