### ISSUE TITLE
Map out all possible ledger errors

### ISSUE THREAD

**Issue by faboweb** [cosmos/voyager#1919]
In cases of ledger errors we sometimes do not handle them gracefully.

Scope:
- [ ] Write down all possible errors we do not handle
- [ ] create an issue to implement error handling

Errors:
- [ ] Trying to connect and then stop trying to connect still renders error notifications after timeout
- [ ] Disconnecting before sending a tx "freezes" the action modal (can't do any action other than wait for timeout)
- [x] Error notification body is `{}` #1977 
- [x] `response.slice is not a function when ledger` is not connected https://github.com/ZondaX/ledger-cosmos-js/issues/10
- [ ] Error on screensaver mode #2005 
- [ ] Handle signature rejection
